ci/release: Use latest Go
Release build broke: https://github.com/uber-go/gopatch/actions/runs/4602492842/jobs/8131507920

```
go: downloading golang.org/x/sys v0.6.0
go: downloading github.com/google/go-intervals v0.0.2
go: downloading golang.org/x/mod v0.9.0
# github.com/uber-go/gopatch/internal/goast
Error: internal/goast/pos.go:35:21: undefined: any
Error: internal/goast/pos.go:44:18: undefined: any
note: module requires Go 1.18
# github.com/uber-go/gopatch/internal/data
Error: internal/data/data.go:35:11: undefined: any
Error: internal/data/data.go:38:10: undefined: any
Error: internal/data/data.go:48:30: undefined: any
Error: internal/data/data.go:49:27: undefined: any
Error: internal/data/data.go:64:29: undefined: any
Error: internal/data/data.go:74:7: undefined: any
Error: internal/data/data.go:77:30: undefined: any
Error: internal/data/data.go:81:29: undefined: any
```

This needs at least Go 1.18 or higher.

Refs #97